/* Generated by port/mktiles.py from the Amiga Larn tiles (web/tiles.png,
 * 8x16, 32 per row). Do not edit. -1 = nothing, -2 = wall, -3 = mountain
 * (autotiled by neighbours: wall_tile / mountain_tile, bits 1 up 2 right
 * 4 down 8 left). Arrays are indexed by the game's enums. */
static const short mon_tile[65] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64};
static const short lt_tile[12] = {-1,-3,65,66,67,68,69,70,71,72,73,-2};
static const short so_tile[26] = {-1,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,89,90,91,92,93,94,95,96,97};
static const short trap_tile[9] = {-1,98,99,100,101,102,103,104,105};
static const short it_tile[12] = {-1,106,107,108,109,110,111,112,113,114,115,116};
static const short ammo_tile[5] = {117,118,107,107,119};
static const short armour_tile[18] = {120,121,122,122,108,123,124,125,126,127,128,129,130,130,131,132,133,134};
static const short container_tile[4] = {135,110,110,136};
static const short gem_tile[4] = {111,137,138,139};
static const short weapon_tile[25] = {140,140,141,142,142,142,143,143,143,144,144,145,146,147,148,144,116,116,149,150,151,152,153,154,146};
static const short amulet_flavour_tile[9] = {106,155,156,157,158,159,160,161,162};
static const short ring_flavour_tile[8] = {163,114,164,165,166,167,168,169};
static const short potion_tile[26] = {113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113};
static const short scroll_tile[25] = {115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115};
static const short book_tile[37] = {109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109,109};
static const short wall_tile[16] = {170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185};
static const short mountain_tile[16] = {186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201};
#define PLAYER_TILE 202
#define SPHERE_TILE 203
#define TILES_PER_ROW 32
#define TILE_COUNT 204
